<a href="https://colab.research.google.com/github/mahirezuhalozdemir/Deep_Learning_Tutorial/blob/main/Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PANDAS LIBRARY**

In [1]:
import pandas as pd

**CHECK PANDAS VERSION**

In [2]:
pd.__version__

'1.5.3'

**CREATE PANDAS DATAFRAME**

In [4]:
dataset = { 'name': ['ahmet','mehmet','ali','veli'],
            'major': ['cs','medicine','math','physic']}

data_frame = pd.DataFrame(dataset)
data_frame

     name     major
0   ahmet        cs
1  mehmet  medicine
2     ali      math
3    veli    physic

**CREATE PANDAS SERIES FROM LIST**

In [6]:
serie = [11, 12, 13, 14, 15]
pandas_serie = pd.Series(serie)
pandas_serie

0    11
1    12
2    13
3    14
4    15
dtype: int64

**CREATE INDEX LABEL**

In [10]:
serie = [1,2,3,4]
index_serie = pd.Series(serie, index=['a','b','c','d'])
print(index_serie)
print('********')
print(index_serie['a'])

a    1
b    2
c    3
d    4
dtype: int64
********
1

**PANDAS SERIES FROM DICTIONARY**

In [12]:
dictionary = {'bmw':2014, 'audi':2020, 'porsche': 2023}
pandas_serie = pd.Series(dictionary)
pandas_serie

bmw        2014
audi       2020
porsche    2023
dtype: int64

**DATAFRAME FEATURES**

In [13]:
data = { 'student': ['ahmet', 'mehmet', 'ali', 'veli'],
         'number': [12, 13, 44, 88],
         'exam_point': [78, 67, 43, 89]}

data_frame = pd.DataFrame(data)

**ACCESING THE DATAFRAME**

In [15]:
#dataframe first row
data_frame.loc[0]

student       ahmet
number           12
exam_point       78
Name: 0, dtype: object

In [18]:
#dataframe first and second row
data_frame.loc[[0, 1]]

  student  number  exam_point
0   ahmet      12          78
1  mehmet      13          67

**LOAD CSV FILE**

In [27]:
df = pd.read_csv('/content/drive/My Drive/Data-cleaning-for-beginners-using-pandas.csv')
#print first 5 rows
df.head()

   Index   Age     Salary  Rating       Location  Established Easy Apply
0      0  44.0  $44k-$99k     5.4       India,In         1999       TRUE
1      1  66.0  $55k-$66k     3.5    New York,Ny         2002       TRUE
2      2   NaN  $77k-$89k    -1.0    New York,Ny           -1         -1
3      3  64.0  $44k-$99k     4.4       India In         1988         -1
4      4  25.0  $44k-$99k     6.4  Australia Aus         2002         -1

In [28]:
#print last 5 rows
df.tail()

    Index   Age     Salary  Rating       Location  Established Easy Apply
24     24  13.0  $44k-$99k    -1.0    New York,Ny         1987         -1
25     25  55.0  $44k-$99k     0.0  Australia Aus         1980       TRUE
26     26   NaN  $55k-$66k     NaN       India,In         1934       TRUE
27     27  52.0  $44k-$99k     5.4       India,In         1935         -1
28     28   NaN  $39k-$88k     3.4  Australia Aus         1932         -1

**GET DATAFRAME INFORMATION**

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        29 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       29 non-null     object
 3   Rating       28 non-null     float64
 4   Location     29 non-null     object
 5   Established  29 non-null     int64
 6   Easy Apply   29 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.7+ KB

**DATAFRAME COLUMNS**

In [32]:
df['Age'].head()

0    44.0
1    66.0
2     NaN
3    64.0
4    25.0
Name: Age, dtype: float64

**SET SPESIFIC VALUE TO DATAFRAME COLUMN**

In [38]:
df['Salary'] = 1000
df['Salary'].head()

0    1000
1    1000
2    1000
3    1000
4    1000
Name: Salary, dtype: int64

In [39]:
df['Salary'] *= 2
df['Salary'].head()

0    2000
1    2000
2    2000
3    2000
4    2000
Name: Salary, dtype: int64

**GET THE SUM OF THE COLUMN**

In [40]:
df['Salary'].sum()

58000

**GET THE MEAN OF THE COLUMN**

In [42]:
df['Salary'].mean()

2000.0

**GET THE NOT EMPTY ROWS**

In [45]:
df.dropna()

    Index   Age  Salary  Rating       Location  Established Easy Apply
0       0  44.0    2000     5.4       India,In         1999       TRUE
1       1  66.0    2000     3.5    New York,Ny         2002       TRUE
3       3  64.0    2000     4.4       India In         1988         -1
4       4  25.0    2000     6.4  Australia Aus         2002         -1
5       5  44.0    2000     1.4       India,In         1999       TRUE
6       6  21.0    2000     0.0    New York,Ny           -1         -1
7       7  44.0    2000    -1.0  Australia Aus           -1         -1
8       8  35.0    2000     5.4    New York,Ny           -1         -1
9       9  22.0    2000     7.7       India,In           -1       TRUE
10     10  55.0    2000     5.4       India,In         2008       TRUE
11     11  44.0    2000     6.7       India,In         2009         -1
13     13  25.0    2000    -1.0  Australia Aus         2019       TRUE
14     14  66.0    2000     4.0  Australia Aus         2020       TRUE
15     15  44.0    2000     3.0  Australia Aus         1999         -1
16     16  19.0    2000     4.5       India,In         1984         -1
18     18  35.0    2000     6.7    New York,Ny         1954       TRUE
19     19  32.0    2000     3.3    New York,Ny         1955       TRUE
21     21  35.0    2000     5.0    New York,Ny         1946         -1
22     22  19.0    2000     7.8    New York,Ny         1988       TRUE
24     24  13.0    2000    -1.0    New York,Ny         1987         -1
25     25  55.0    2000     0.0  Australia Aus         1980       TRUE
27     27  52.0    2000     5.4       India,In         1935         -1

**GET ALL NON-NULL NUMBERS FOR COLUMNS**

In [47]:
df.dropna().count()

Index          22
Age            22
Salary         22
Rating         22
Location       22
Established    22
Easy Apply     22
dtype: int64

**CHANGE DATAFRAME FOR NOT-NULL ROWS**

In [54]:
df.dropna(inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 27
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Index        22 non-null     int64
 1   Age          22 non-null     float64
 2   Salary       22 non-null     int64
 3   Rating       22 non-null     float64
 4   Location     22 non-null     object
 5   Established  22 non-null     int64
 6   Easy Apply   22 non-null     object
dtypes: float64(2), int64(3), object(2)
memory usage: 1.4+ KB

**REPLACE NULL VALUES WITH THE SPECIFIC NUMBER**

In [66]:
#replace null values with 1000
df.fillna(1000, inplace = True)
df

    Index   Age  Salary  Rating       Location  Established Easy Apply
0       0  44.0    2000     5.4       India,In         1999       TRUE
1       1  66.0    2000     3.5    New York,Ny         2002       TRUE
3       3  64.0    2000     4.4       India In         1988         -1
4       4  25.0    2000     6.4  Australia Aus         2002         -1
5       5  44.0    2000     1.4       India,In         1999       TRUE
6       6  21.0    2000     0.0    New York,Ny           -1         -1
7       7  44.0    2000    -1.0  Australia Aus           -1         -1
8       8  35.0    2000     5.4    New York,Ny           -1         -1
9       9  22.0    2000     7.7       India,In           -1       TRUE
10     10  55.0    2000     5.4       India,In         2008       TRUE
11     11  44.0    2000     6.7       India,In         2009         -1
13     13  25.0    2000    -1.0  Australia Aus         2019       TRUE
14     14  66.0    2000     4.0  Australia Aus         2020       TRUE
15     15  44.0    2000     3.0  Australia Aus         1999         -1
16     16  19.0    2000     4.5       India,In         1984         -1
18     18  35.0    2000     6.7    New York,Ny         1954       TRUE
19     19  32.0    2000     3.3    New York,Ny         1955       TRUE
21     21  35.0    2000     5.0    New York,Ny         1946         -1
22     22  19.0    2000     7.8    New York,Ny         1988       TRUE
24     24  13.0    2000    -1.0    New York,Ny         1987         -1
25     25  55.0    2000     0.0  Australia Aus         1980       TRUE
27     27  52.0    2000     5.4       India,In         1935         -1

In [67]:
#replace null values with 1000
df['Salary'].fillna(1000, inplace = True)
df

    Index   Age  Salary  Rating       Location  Established Easy Apply
0       0  44.0    2000     5.4       India,In         1999       TRUE
1       1  66.0    2000     3.5    New York,Ny         2002       TRUE
3       3  64.0    2000     4.4       India In         1988         -1
4       4  25.0    2000     6.4  Australia Aus         2002         -1
5       5  44.0    2000     1.4       India,In         1999       TRUE
6       6  21.0    2000     0.0    New York,Ny           -1         -1
7       7  44.0    2000    -1.0  Australia Aus           -1         -1
8       8  35.0    2000     5.4    New York,Ny           -1         -1
9       9  22.0    2000     7.7       India,In           -1       TRUE
10     10  55.0    2000     5.4       India,In         2008       TRUE
11     11  44.0    2000     6.7       India,In         2009         -1
13     13  25.0    2000    -1.0  Australia Aus         2019       TRUE
14     14  66.0    2000     4.0  Australia Aus         2020       TRUE
15     15  44.0    2000     3.0  Australia Aus         1999         -1
16     16  19.0    2000     4.5       India,In         1984         -1
18     18  35.0    2000     6.7    New York,Ny         1954       TRUE
19     19  32.0    2000     3.3    New York,Ny         1955       TRUE
21     21  35.0    2000     5.0    New York,Ny         1946         -1
22     22  19.0    2000     7.8    New York,Ny         1988       TRUE
24     24  13.0    2000    -1.0    New York,Ny         1987         -1
25     25  55.0    2000     0.0  Australia Aus         1980       TRUE
27     27  52.0    2000     5.4       India,In         1935         -1

**GET NULL ROWS FOR ALL COLUMNS**

In [48]:
df.isnull().sum()

Index          0
Age            7
Salary         0
Rating         1
Location       0
Established    0
Easy Apply     0
dtype: int64

In [50]:
df.isnull().head()

   Index    Age  Salary  Rating  Location  Established  Easy Apply
0  False  False   False   False     False        False       False
1  False  False   False   False     False        False       False
2  False   True   False   False     False        False       False
3  False  False   False   False     False        False       False
4  False  False   False   False     False        False       False

**TRANSPOSE OF DATAFRAME**

In [62]:
df.T

,0,1,3,4,5,6,7,8,9,10,...,14,15,16,18,19,21,22,24,25,27
Index,0,1,3,4,5,6,7,8,9,10,...,14,15,16,18,19,21,22,24,25,27
Age,44.0,66.0,64.0,25.0,44.0,21.0,44.0,35.0,22.0,55.0,...,66.0,44.0,19.0,35.0,32.0,35.0,19.0,13.0,55.0,52.0
Salary,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000,...,2000,2000,2000,2000,2000,2000,2000,2000,2000,2000
Rating,5.4,3.5,4.4,6.4,1.4,0.0,-1.0,5.4,7.7,5.4,...,4.0,3.0,4.5,6.7,3.3,5.0,7.8,-1.0,0.0,5.4
Location,"India,In","New York,Ny",India In,Australia Aus,"India,In","New York,Ny",Australia Aus,"New York,Ny","India,In","India,In",...,Australia Aus,Australia Aus,"India,In","New York,Ny","New York,Ny","New York,Ny","New York,Ny","New York,Ny",Australia Aus,"India,In"
Established,1999,2002,1988,2002,1999,-1,-1,-1,-1,2008,...,2020,1999,1984,1954,1955,1946,1988,1987,1980,1935
Easy Apply,TRUE,TRUE,-1,-1,TRUE,-1,-1,-1,TRUE,TRUE,...,TRUE,-1,-1,TRUE,TRUE,-1,TRUE,-1,TRUE,-1

**STATISTICAL SUMMARY OF DATAFRAME**

In [58]:
df.describe()

           Index        Age  Salary     Rating  Established
count  22.000000  22.000000    22.0  22.000000    22.000000
mean   12.636364  39.045455  2000.0   3.772727  1625.909091
std     8.092003  16.134781     0.0   2.862597   785.297875
min     0.000000  13.000000  2000.0  -1.000000    -1.000000
25%     6.250000  25.000000  2000.0   1.800000  1948.000000
50%    12.000000  39.500000  2000.0   4.450000  1987.500000
75%    18.750000  50.000000  2000.0   5.400000  2001.250000
max    27.000000  66.000000  2000.0   7.800000  2020.000000

**GET DATAS WITH LOCATION**

In [65]:
#get the value of the dataframe in the first row and 3rd column
df.iloc[0,3]

5.4